// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PlatformGrainBehavior { overlay, darkOnly }

enum PlatformCameraLensDirection {
  /// Front facing camera (a user looking at the screen is seen by the camera).
  front,

  /// Back facing camera (a user looking at the screen is not seen by the camera).
  back,

  /// External camera which may not be mounted to the device.
  external,
}

enum PlatformCameraLensType {
  /// A built-in wide-angle camera device type.
  wide,

  /// A built-in camera device type with a longer focal length than a wide-angle camera.
  telephoto,

  /// A built-in camera device type with a shorter focal length than a wide-angle camera.
  ultraWide,

  /// Unknown camera device type.
  unknown,
}

enum PlatformDeviceOrientation { portraitUp, landscapeLeft, portraitDown, landscapeRight }

enum PlatformExposureMode { auto, locked }

enum PlatformFlashMode { off, auto, always, torch }

enum PlatformFocusMode { auto, locked }

/// Pigeon version of ImageFileFormat.
enum PlatformImageFileFormat { jpeg, heif }

enum PlatformImageFormatGroup { bgra8888, yuv420 }

enum PlatformResolutionPreset {
  low,
  medium,
  high,
  veryHigh,
  ultraHigh,
  max,

  /// Maps to `AVCaptureSession.Preset.photo` — full-sensor stills at the
  /// cost of a reduced video stream. See `ResolutionPreset.photo`.
  photo,
}

enum PlatformVideoStabilizationMode { off, standard, cinematic, cinematicExtended }

class PlatformCameraDescription {
  PlatformCameraDescription({
    required this.name,
    required this.lensDirection,
    required this.lensType,
    this.equivalentFocalLength,
  });

  /// The name of the camera device.
  String name;

  /// The direction the camera is facing.
  PlatformCameraLensDirection lensDirection;

  /// The type of the camera lens.
  PlatformCameraLensType lensType;

  /// The approximate 35mm-equivalent focal length of the lens, in millimetres.
  ///
  /// Only populated on iOS (AVFoundation). Null on other platforms.
  double? equivalentFocalLength;

  List<Object?> _toList() {
    return <Object?>[name, lensDirection, lensType, equivalentFocalLength];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraDescription decode(Object result) {
    result as List<Object?>;
    return PlatformCameraDescription(
      name: result[0]! as String,
      lensDirection: result[1]! as PlatformCameraLensDirection,
      lensType: result[2]! as PlatformCameraLensType,
      equivalentFocalLength: result[3] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraDescription || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(lensDirection, other.lensDirection) &&
        _deepEquals(lensType, other.lensType) &&
        _deepEquals(equivalentFocalLength, other.equivalentFocalLength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCameraDescription(name: $name, lensDirection: $lensDirection, lensType: $lensType, equivalentFocalLength: $equivalentFocalLength)';
  }
}

class PlatformCameraState {
  PlatformCameraState({
    required this.previewSize,
    required this.exposureMode,
    required this.focusMode,
    required this.exposurePointSupported,
    required this.focusPointSupported,
  });

  /// The size of the preview, in pixels.
  PlatformSize previewSize;

  /// The default exposure mode
  PlatformExposureMode exposureMode;

  /// The default focus mode
  PlatformFocusMode focusMode;

  /// Whether setting exposure points is supported.
  bool exposurePointSupported;

  /// Whether setting focus points is supported.
  bool focusPointSupported;

  List<Object?> _toList() {
    return <Object?>[
      previewSize,
      exposureMode,
      focusMode,
      exposurePointSupported,
      focusPointSupported,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraState decode(Object result) {
    result as List<Object?>;
    return PlatformCameraState(
      previewSize: result[0]! as PlatformSize,
      exposureMode: result[1]! as PlatformExposureMode,
      focusMode: result[2]! as PlatformFocusMode,
      exposurePointSupported: result[3]! as bool,
      focusPointSupported: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(previewSize, other.previewSize) &&
        _deepEquals(exposureMode, other.exposureMode) &&
        _deepEquals(focusMode, other.focusMode) &&
        _deepEquals(exposurePointSupported, other.exposurePointSupported) &&
        _deepEquals(focusPointSupported, other.focusPointSupported);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCameraState(previewSize: $previewSize, exposureMode: $exposureMode, focusMode: $focusMode, exposurePointSupported: $exposurePointSupported, focusPointSupported: $focusPointSupported)';
  }
}

class PlatformCameraImageData {
  PlatformCameraImageData({
    required this.formatCode,
    required this.width,
    required this.height,
    required this.planes,
    required this.lensAperture,
    required this.sensorExposureTimeNanoseconds,
    required this.sensorSensitivity,
  });

  /// The FourCharCode of the image format.
  int formatCode;

  int width;

  int height;

  List<PlatformCameraImagePlane> planes;

  double lensAperture;

  int sensorExposureTimeNanoseconds;

  double sensorSensitivity;

  List<Object?> _toList() {
    return <Object?>[
      formatCode,
      width,
      height,
      planes,
      lensAperture,
      sensorExposureTimeNanoseconds,
      sensorSensitivity,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraImageData decode(Object result) {
    result as List<Object?>;
    return PlatformCameraImageData(
      formatCode: result[0]! as int,
      width: result[1]! as int,
      height: result[2]! as int,
      planes: (result[3]! as List<Object?>).cast<PlatformCameraImagePlane>(),
      lensAperture: result[4]! as double,
      sensorExposureTimeNanoseconds: result[5]! as int,
      sensorSensitivity: result[6]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraImageData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(formatCode, other.formatCode) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(planes, other.planes) &&
        _deepEquals(lensAperture, other.lensAperture) &&
        _deepEquals(sensorExposureTimeNanoseconds, other.sensorExposureTimeNanoseconds) &&
        _deepEquals(sensorSensitivity, other.sensorSensitivity);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCameraImageData(formatCode: $formatCode, width: $width, height: $height, planes: $planes, lensAperture: $lensAperture, sensorExposureTimeNanoseconds: $sensorExposureTimeNanoseconds, sensorSensitivity: $sensorSensitivity)';
  }
}

class PlatformCameraImagePlane {
  PlatformCameraImagePlane({
    required this.bytes,
    required this.bytesPerRow,
    required this.width,
    required this.height,
  });

  Uint8List bytes;

  int bytesPerRow;

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[bytes, bytesPerRow, width, height];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraImagePlane decode(Object result) {
    result as List<Object?>;
    return PlatformCameraImagePlane(
      bytes: result[0]! as Uint8List,
      bytesPerRow: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraImagePlane || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bytes, other.bytes) &&
        _deepEquals(bytesPerRow, other.bytesPerRow) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCameraImagePlane(bytes: $bytes, bytesPerRow: $bytesPerRow, width: $width, height: $height)';
  }
}

class PlatformMediaSettings {
  PlatformMediaSettings({
    required this.resolutionPreset,
    this.framesPerSecond,
    this.videoBitrate,
    this.audioBitrate,
    required this.enableAudio,
    this.aspectRatio,
  });

  PlatformResolutionPreset resolutionPreset;

  int? framesPerSecond;

  int? videoBitrate;

  int? audioBitrate;

  bool enableAudio;

  /// Aspect ratio (width/height) that center-crops preview, photo, and video
  /// output. `null` means no crop. Only takes effect when the shader pipeline
  /// is enabled.
  double? aspectRatio;

  List<Object?> _toList() {
    return <Object?>[
      resolutionPreset,
      framesPerSecond,
      videoBitrate,
      audioBitrate,
      enableAudio,
      aspectRatio,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMediaSettings decode(Object result) {
    result as List<Object?>;
    return PlatformMediaSettings(
      resolutionPreset: result[0]! as PlatformResolutionPreset,
      framesPerSecond: result[1] as int?,
      videoBitrate: result[2] as int?,
      audioBitrate: result[3] as int?,
      enableAudio: result[4]! as bool,
      aspectRatio: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMediaSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(resolutionPreset, other.resolutionPreset) &&
        _deepEquals(framesPerSecond, other.framesPerSecond) &&
        _deepEquals(videoBitrate, other.videoBitrate) &&
        _deepEquals(audioBitrate, other.audioBitrate) &&
        _deepEquals(enableAudio, other.enableAudio) &&
        _deepEquals(aspectRatio, other.aspectRatio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformMediaSettings(resolutionPreset: $resolutionPreset, framesPerSecond: $framesPerSecond, videoBitrate: $videoBitrate, audioBitrate: $audioBitrate, enableAudio: $enableAudio, aspectRatio: $aspectRatio)';
  }
}

class PlatformPoint {
  PlatformPoint({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPoint decode(Object result) {
    result as List<Object?>;
    return PlatformPoint(x: result[0]! as double, y: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPoint || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPoint(x: $x, y: $y)';
  }
}

class PlatformSize {
  PlatformSize({required this.width, required this.height});

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[width, height];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSize decode(Object result) {
    result as List<Object?>;
    return PlatformSize(width: result[0]! as double, height: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSize(width: $width, height: $height)';
  }
}

class PlatformEffectsValues {
  PlatformEffectsValues({
    required this.vignetteIntensity,
    this.grainNoisePath,
    required this.grainOpacity,
    required this.grainSize,
    required this.grainBehavior,
    this.lutFilePath,
    required this.lutIntensity,
    required this.resolution,
    required this.colorShift,
    required this.mist,
    required this.prism,
    required this.cheapFisheye,
    required this.bloom,
    required this.diffusion,
  });

  /// Radial darkening toward the frame edges (0.0 = off, 1.0 = full vignette).
  double vignetteIntensity;

  /// Absolute file path to the grain/noise source image.
  /// Null disables the grain effect.
  String? grainNoisePath;

  /// Opacity of the grain overlay (0.0 = off, 1.0 = fully applied).
  double grainOpacity;

  /// Resolution-independent grain tile size (>= 0.0).
  /// 1.0 = grain image spans the full frame; smaller values tile more finely; bigger values tile more coarsely.
  double grainSize;

  /// Controls where grain is visible across the tonal range.
  PlatformGrainBehavior grainBehavior;

  /// Absolute file path to a 3D LUT color-grade image: a 512×512 PNG storing
  /// a 64×64×64 cube as an 8×8 row-major grid of 64×64 tiles (tile index =
  /// blue slice; within a tile x = red, y = green top-to-bottom).
  /// Null disables the LUT color filter.
  String? lutFilePath;

  /// Intensity of the LUT color filter (0.0 = no effect, 1.0 = full LUT).
  /// Ignored when [lutFilePath] is null.
  double lutIntensity;

  /// Simulates a low-resolution sensor (0.0 = off, 1.0 = full strength).
  /// Adds a soft Gaussian blur and desaturation.
  double resolution;

  /// Chromatic aberration strength (0.0 = off, 1.0 = full strength).
  double colorShift;

  /// Dreamy mist / Orton-style soft glow (0.0 = off, 1.0 = full strength).
  double mist;

  /// Radial chromatic motion blur (0.0 = off, 1.0 = full strength).
  double prism;

  /// Cheap clip-on fisheye lens simulation (true = on).
  bool cheapFisheye;

  /// Highlight bloom / light-bleed glow (0.0 = off, 1.0 = full strength).
  double bloom;

  /// Diffusion / soft-focus filter (0.0 = off, 1.0 = full strength).
  /// Mixes the frame toward a wide Gaussian blur of itself.
  double diffusion;

  List<Object?> _toList() {
    return <Object?>[
      vignetteIntensity,
      grainNoisePath,
      grainOpacity,
      grainSize,
      grainBehavior,
      lutFilePath,
      lutIntensity,
      resolution,
      colorShift,
      mist,
      prism,
      cheapFisheye,
      bloom,
      diffusion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformEffectsValues decode(Object result) {
    result as List<Object?>;
    return PlatformEffectsValues(
      vignetteIntensity: result[0]! as double,
      grainNoisePath: result[1] as String?,
      grainOpacity: result[2]! as double,
      grainSize: result[3]! as double,
      grainBehavior: result[4]! as PlatformGrainBehavior,
      lutFilePath: result[5] as String?,
      lutIntensity: result[6]! as double,
      resolution: result[7]! as double,
      colorShift: result[8]! as double,
      mist: result[9]! as double,
      prism: result[10]! as double,
      cheapFisheye: result[11]! as bool,
      bloom: result[12]! as double,
      diffusion: result[13]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformEffectsValues || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(vignetteIntensity, other.vignetteIntensity) &&
        _deepEquals(grainNoisePath, other.grainNoisePath) &&
        _deepEquals(grainOpacity, other.grainOpacity) &&
        _deepEquals(grainSize, other.grainSize) &&
        _deepEquals(grainBehavior, other.grainBehavior) &&
        _deepEquals(lutFilePath, other.lutFilePath) &&
        _deepEquals(lutIntensity, other.lutIntensity) &&
        _deepEquals(resolution, other.resolution) &&
        _deepEquals(colorShift, other.colorShift) &&
        _deepEquals(mist, other.mist) &&
        _deepEquals(prism, other.prism) &&
        _deepEquals(cheapFisheye, other.cheapFisheye) &&
        _deepEquals(bloom, other.bloom) &&
        _deepEquals(diffusion, other.diffusion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformEffectsValues(vignetteIntensity: $vignetteIntensity, grainNoisePath: $grainNoisePath, grainOpacity: $grainOpacity, grainSize: $grainSize, grainBehavior: $grainBehavior, lutFilePath: $lutFilePath, lutIntensity: $lutIntensity, resolution: $resolution, colorShift: $colorShift, mist: $mist, prism: $prism, cheapFisheye: $cheapFisheye, bloom: $bloom, diffusion: $diffusion)';
  }
}

/// Paths to the two photo files produced by [CameraApi.takePictureWithOriginal].
class PlatformCapturedPicturePaths {
  PlatformCapturedPicturePaths({required this.originalPath, required this.processedPath});

  /// File path of the un-effected original. The configured `captureScale` crop
  /// and resampling is preserved, but the custom Metal shader is not applied.
  String originalPath;

  /// File path of the shader-processed photo (equivalent to
  /// [CameraApi.takePicture]).
  String processedPath;

  List<Object?> _toList() {
    return <Object?>[originalPath, processedPath];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCapturedPicturePaths decode(Object result) {
    result as List<Object?>;
    return PlatformCapturedPicturePaths(
      originalPath: result[0]! as String,
      processedPath: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCapturedPicturePaths || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(originalPath, other.originalPath) &&
        _deepEquals(processedPath, other.processedPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCapturedPicturePaths(originalPath: $originalPath, processedPath: $processedPath)';
  }
}

/// Pigeon version of WhiteBalanceValues.
class PlatformWhiteBalanceValues {
  PlatformWhiteBalanceValues({required this.temperature, required this.tint});

  /// The color temperature in Kelvin.
  double temperature;

  /// The tint offset, where `0` is neutral.
  double tint;

  List<Object?> _toList() {
    return <Object?>[temperature, tint];
  }

  Object encode() {
    return _toList();
  }

  static PlatformWhiteBalanceValues decode(Object result) {
    result as List<Object?>;
    return PlatformWhiteBalanceValues(
      temperature: result[0]! as double,
      tint: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformWhiteBalanceValues || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(temperature, other.temperature) && _deepEquals(tint, other.tint);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformWhiteBalanceValues(temperature: $temperature, tint: $tint)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformGrainBehavior) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraLensDirection) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraLensType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformDeviceOrientation) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformExposureMode) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is PlatformFlashMode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PlatformFocusMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is PlatformImageFileFormat) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is PlatformImageFormatGroup) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is PlatformResolutionPreset) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is PlatformVideoStabilizationMode) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is PlatformCameraDescription) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraState) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraImageData) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraImagePlane) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMediaSettings) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPoint) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is PlatformSize) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PlatformEffectsValues) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCapturedPicturePaths) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is PlatformWhiteBalanceValues) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformGrainBehavior.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCameraLensDirection.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCameraLensType.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformDeviceOrientation.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformExposureMode.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformFlashMode.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformFocusMode.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformImageFileFormat.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformImageFormatGroup.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformResolutionPreset.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformVideoStabilizationMode.values[value];
      case 140:
        return PlatformCameraDescription.decode(readValue(buffer)!);
      case 141:
        return PlatformCameraState.decode(readValue(buffer)!);
      case 142:
        return PlatformCameraImageData.decode(readValue(buffer)!);
      case 143:
        return PlatformCameraImagePlane.decode(readValue(buffer)!);
      case 144:
        return PlatformMediaSettings.decode(readValue(buffer)!);
      case 145:
        return PlatformPoint.decode(readValue(buffer)!);
      case 146:
        return PlatformSize.decode(readValue(buffer)!);
      case 147:
        return PlatformEffectsValues.decode(readValue(buffer)!);
      case 148:
        return PlatformCapturedPicturePaths.decode(readValue(buffer)!);
      case 149:
        return PlatformWhiteBalanceValues.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class CameraApi {
  /// Constructor for [CameraApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CameraApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Returns the list of available cameras.
  Future<List<PlatformCameraDescription>> getAvailableCameras() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getAvailableCameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PlatformCameraDescription>();
  }

  /// Create a new camera with the given settings, and returns its ID.
  /// Every preview frame, recorded video frame, and captured photo is
  /// rendered through the bundled Metal shader pipeline; when no effects or
  /// crop are applied the pipeline is a pass-through.
  Future<int> create(String cameraName, PlatformMediaSettings settings) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      cameraName,
      settings,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Initializes the camera with the given ID.
  Future<void> initialize(int cameraId, PlatformImageFormatGroup imageFormat) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      cameraId,
      imageFormat,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Begins streaming frames from the camera.
  Future<void> startImageStream() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.startImageStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Stops streaming frames from the camera.
  Future<void> stopImageStream() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.stopImageStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Called by the Dart side of the plugin when it has received the last image
  /// frame sent.
  ///
  /// This is used to throttle sending frames across the channel.
  Future<void> receivedImageStreamData() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.receivedImageStreamData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Indicates that the given camera is no longer being used on the Dart side,
  /// and any associated resources can be cleaned up.
  Future<void> dispose(int cameraId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cameraId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Locks the camera capture to the current device orientation.
  Future<void> lockCaptureOrientation(PlatformDeviceOrientation orientation) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.lockCaptureOrientation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[orientation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Unlocks camera capture orientation, allowing it to automatically adapt to
  /// device orientation.
  Future<void> unlockCaptureOrientation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.unlockCaptureOrientation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Takes a picture with the current settings, and returns the path to the
  /// resulting file.
  Future<String> takePicture() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.takePicture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Takes a picture and saves it twice: the un-effected original (with the
  /// configured `captureScale` crop preserved) and the shader-processed
  /// version. Returns the paths to both files.
  Future<PlatformCapturedPicturePaths> takePictureWithOriginal() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.takePictureWithOriginal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformCapturedPicturePaths;
  }

  /// Does any preprocessing necessary before beginning to record video.
  Future<void> prepareForVideoRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.prepareForVideoRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Begins recording video, optionally enabling streaming to Dart at the same
  /// time.
  Future<void> startVideoRecording(bool enableStream) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.startVideoRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enableStream]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Stops recording video, and results the path to the resulting file.
  Future<String> stopVideoRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.stopVideoRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Pauses video recording.
  Future<void> pauseVideoRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.pauseVideoRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Resumes a previously paused video recording.
  Future<void> resumeVideoRecording() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.resumeVideoRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Switches the camera to the given flash mode.
  Future<void> setFlashMode(PlatformFlashMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setFlashMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Returns the flash modes supported by the camera.
  Future<List<PlatformFlashMode>> getSupportedFlashModes() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getSupportedFlashModes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PlatformFlashMode>();
  }

  /// Switches the camera to the given exposure mode.
  Future<void> setExposureMode(PlatformExposureMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setExposureMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Anchors auto-exposure to the given point in (0,1) coordinate space.
  ///
  /// A null value resets to the default exposure point.
  Future<void> setExposurePoint(PlatformPoint? point) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setExposurePoint$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[point]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Returns the minimum exposure offset supported by the camera.
  Future<double> getMinExposureOffset() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getMinExposureOffset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  /// Returns the maximum exposure offset supported by the camera.
  Future<double> getMaxExposureOffset() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getMaxExposureOffset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  /// Sets the exposure offset manually to the given value.
  Future<void> setExposureOffset(double offset) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setExposureOffset$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[offset]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Switches the camera to the given focus mode.
  Future<void> setFocusMode(PlatformFocusMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setFocusMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Anchors auto-focus to the given point in (0,1) coordinate space.
  ///
  /// A null value resets to the default focus point.
  Future<void> setFocusPoint(PlatformPoint? point) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setFocusPoint$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[point]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the white balance for the camera.
  ///
  /// Null enables automatic white balance; a non-null value locks the white
  /// balance to the given temperature and tint.
  Future<void> setWhiteBalance(PlatformWhiteBalanceValues? values) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setWhiteBalance$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[values]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Gets whether the camera can lock its white balance to a given temperature
  /// and tint.
  Future<bool> isWhiteBalanceSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.isWhiteBalanceSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the minimum zoom level supported by the camera.
  Future<double> getMinZoomLevel() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getMinZoomLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  /// Returns the maximum zoom level supported by the camera.
  Future<double> getMaxZoomLevel() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.getMaxZoomLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  /// Sets the zoom factor.
  Future<void> setZoomLevel(double zoom) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setZoomLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[zoom]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the video stabilization mode.
  Future<void> setVideoStabilizationMode(PlatformVideoStabilizationMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setVideoStabilizationMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Gets if the given video stabilization mode is supported.
  Future<bool> isVideoStabilizationModeSupported(PlatformVideoStabilizationMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.isVideoStabilizationModeSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Pauses streaming of preview frames.
  Future<void> pausePreview() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.pausePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Resumes a previously paused preview stream.
  Future<void> resumePreview() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.resumePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Changes the camera used while recording video.
  ///
  /// This should only be called while video recording is active.
  Future<void> updateDescriptionWhileRecording(String cameraName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.updateDescriptionWhileRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cameraName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the file format used for taking pictures.
  Future<void> setImageFileFormat(PlatformImageFileFormat format) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setImageFileFormat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[format]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the JPEG compression quality for still image capture.
  Future<void> setJpegImageQuality(int quality) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setJpegImageQuality$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[quality]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Applies visual effect parameters to the Metal shader pipeline.
  /// Has no effect when no shader pipeline is active.
  Future<void> setEffectsValues(PlatformEffectsValues values) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setEffectsValues$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[values]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the center-crop aspect ratio (width/height) applied to preview,
  /// photo, and video. Pass `null` to disable cropping. Has no effect when
  /// no shader pipeline is active.
  Future<void> setAspectRatio(double? aspectRatio) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setAspectRatio$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[aspectRatio]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the capture scale (0.1–1.0) applied inside the aspect-ratio crop.
  /// 1.0 means no extra crop. Values below 1.0 narrow the captured area;
  /// the preview shows the full aspect-ratio crop with the area outside the
  /// scaled rectangle darkened, while photo and video files contain only
  /// the scaled rectangle.
  Future<void> setCaptureScale(double scale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setCaptureScale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[scale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Sets the corner radius of the captureScale rectangle in the preview.
  /// The radius is in the range [0.0, 1.0], where 0.0 means square corners
  /// and positive values round the corners of the darkened border.
  /// Only affects the preview; saved photos and videos are unaffected.
  Future<void> setCaptureCornerRadius(double radius) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.camera_avfoundation.CameraApi.setCaptureCornerRadius$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[radius]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}

/// Returns a broadcast [Stream] of events from the `imageDataStream` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformCameraImageData> imageDataStream({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel imageDataStreamChannel = EventChannel(
    'dev.flutter.pigeon.camera_avfoundation.CameraImageStreamEventApi.imageDataStream$instanceName',
    pigeonMethodCodec,
  );
  return imageDataStreamChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformCameraImageData;
  });
}

/// Handler for native callbacks that are not tied to a specific camera ID.
abstract class CameraGlobalEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when the device's physical orientation changes.
  void deviceOrientationChanged(PlatformDeviceOrientation orientation);

  static void setUp(
    CameraGlobalEventApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.camera_avfoundation.CameraGlobalEventApi.deviceOrientationChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformDeviceOrientation arg_orientation = args[0]! as PlatformDeviceOrientation;
          try {
            api.deviceOrientationChanged(arg_orientation);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Handler for native callbacks that are tied to a specific camera ID.
///
/// This is intended to be initialized with the camera ID as a suffix.
abstract class CameraEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when the camera is inialitized for use.
  void initialized(PlatformCameraState initialState);

  /// Called when an error occurs in the camera.
  ///
  /// This should be used for errors that occur outside of the context of
  /// handling a specific HostApi call, such as during streaming.
  void error(String message);

  /// Called when the preview size changes (e.g., after an aspect ratio change).
  void previewSizeChanged(PlatformSize size);

  /// Called while the camera is in auto white balance mode with the
  /// temperature (Kelvin) and tint values currently selected by the
  /// hardware. iOS only.
  void autoWhiteBalanceChanged(double temperature, double tint);

  static void setUp(
    CameraEventApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.camera_avfoundation.CameraEventApi.initialized$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformCameraState arg_initialState = args[0]! as PlatformCameraState;
          try {
            api.initialized(arg_initialState);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.camera_avfoundation.CameraEventApi.error$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_message = args[0]! as String;
          try {
            api.error(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.camera_avfoundation.CameraEventApi.previewSizeChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformSize arg_size = args[0]! as PlatformSize;
          try {
            api.previewSizeChanged(arg_size);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.camera_avfoundation.CameraEventApi.autoWhiteBalanceChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final double arg_temperature = args[0]! as double;
          final double arg_tint = args[1]! as double;
          try {
            api.autoWhiteBalanceChanged(arg_temperature, arg_tint);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
